# Generated by Django 3.1 on 2020-08-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('site_location', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element', models.CharField(max_length=50)),
                ('location', models.URLField()),
                ('require_login', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapper.sitemap')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapper.site')),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability', models.CharField(max_length=100)),
                ('is_reported', models.BooleanField(default=False)),
                ('is_fixed', models.BooleanField(default=False)),
                ('sitemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapper.sitemap')),
            ],
        ),
    ]
