# Generated by Django 3.1 on 2020-08-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='slug',
            field=models.SlugField(default='test', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitemap',
            name='comment',
            field=models.CharField(default='test comment', max_length=500),
            preserve_default=False,
        ),
    ]
