# Generated by Django 3.1 on 2020-08-12 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0002_auto_20200811_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemap',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mapper.sitemap'),
        ),
    ]
