# Generated by Django 3.1 on 2020-08-12 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0003_auto_20200812_0427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemap',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
