# Generated by Django 3.1 on 2020-08-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0005_auto_20200816_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='vulnerability',
            name='category',
            field=models.CharField(choices=[('Critical', 'CRITICAL'), ('High', 'HIGH'), ('Medium', 'MEDIUM'), ('Low', 'LOW'), ('Informational', 'INFORMATIONAL')], default='Low', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
